# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  
  config.vm.define "kali-linux-1" do |node|
    node.vm.box = "kalilinux/rolling"
    node.vm.hostname = "kali-linux-1"

    

    node.vm.provider "virtualbox" do |vb|
      vb.name = "Kali Linux 1"
      vb.memory = "2048"
      vb.cpus = 2
      vb.gui = false
    end

    
  end
  
end